branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Lint / build"
          - "Unit Tests / test"
          - "Playwright Tests / test"
  - name: master
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Lint / build"
          - "Unit Tests / test"
          - "Playwright Tests / test"
