# cloudbuild.yaml
#
# This file defines the CI/CD pipeline for the Benefits Assistant Chatbot.
# It's used by Google Cloud Build to test, build, and deploy the application.

steps:
  # 1. Install Dependencies
  # Using a specific image with node and pnpm pre-installed could speed this up.
  - name: 'node:18'
    id: 'Install Dependencies'
    entrypoint: 'npm'
    args: ['install', '-g', 'pnpm', '&&', 'pnpm', 'install', '--frozen-lockfile']

  # 2. Run Tests
  - name: 'node:18'
    id: 'Run Tests'
    entrypoint: 'pnpm'
    args: ['test']

  # 3. Build the Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args:
      - 'build'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/benefits-chatbot/app:latest'
      - '.'
      - '-f'
      - 'Dockerfile'

  # 4. Push the Docker Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    args: ['push', '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/benefits-chatbot/app:latest']

  # 5. Run Database Migrations Securely
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Run Database Migrations'
    entrypoint: 'bash'
    args: ['./scripts/run-gcp-migrations.sh']
    secretEnv: ['DB_USER', 'DB_PASSWORD', 'DB_NAME']

  # 6. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'benefits-chatbot-app'
      - '--image'
      - '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/benefits-chatbot/app:latest'
      - '--region'
      - '${_GCP_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--quiet'
      - '--update-secrets=DB_USER=DB_USER:latest,DB_PASSWORD=DB_PASSWORD:latest,DB_NAME=DB_NAME:latest,DB_HOST=DB_HOST:latest,DB_PORT=DB_PORT:latest,GCP_PROJECT=GCP_PROJECT:latest,CLOUD_SQL_INSTANCE=CLOUD_SQL_INSTANCE:latest,VERTEX_AI_MODEL=VERTEX_AI_MODEL:latest,GCS_BUCKET_NAME=GCS_BUCKET_NAME:latest'

# Define which secrets from Secret Manager are available to the build steps
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DB_USER/versions/latest
      env: 'DB_USER'
    - versionName: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/latest
      env: 'DB_PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/DB_NAME/versions/latest
      env: 'DB_NAME'

substitutions:
  _GCP_REGION: us-central1

# Define the image that will be produced
images:
  - '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/benefits-chatbot/app:latest'

# Set a timeout for the build
timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
