name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint and tests
        run: pnpm lint && pnpm test

      - name: Build
        run: pnpm build

      - name: Deploy to Firebase Hosting and Functions
        run: pnpm dlx firebase-tools deploy --only hosting,functions --token ${{ secrets.FIREBASE_TOKEN }}

